version: '3.7'
services:
  my-app:
    image: mmoldenburg/fullstack-app-image
    build: 
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/app/
    networks:
      - myNetwork

  server:
    image: mmoldenburg/fullstack-server-image
    build: 
      context: ./server
      dockerfile: Dockerfile
    networks:
      - myNetwork

networks:
  myNetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.255